spring:
  datasource: # Configuração do banco de dados para Produção
    driver-class-name: ${DATABASE_DRIVER} # Driver do DB
    url: ${DATABASE_URL} # URL de conexão do DB
    username: ${DATABASE_USERNAME} # Usuário do DB
    password: ${DATABASE_PASSWORD} # Senha do DB
  hikari: # Configurações do Pool de Conexões HikariCP (para Produção)
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    pool-name: MinhaAppHikariPool # Nome do pool

  jpa:
    # Configuração do Hibernate (JPA) para Produção
    hibernate:
      # Estratégia DDL (validate ou none em PROD!)
      ddl-auto: validate # Ou 'none' (schema gerenciado externamente)
    show-sql: false # DESATIVAR SQL em PROD (desempenho/segurança)
    properties:
      hibernate.dialect: ${HIBERNATE_DIALECT} # Dialeto Hibernate (via variável/default)

  h2:
    console:
      enabled: false # DESATIVAR console H2 em PROD (segurança)

  springdoc:
    api-docs:
      enable: false # DESATIVAR geração OpenAPI em PROD (segurança/desempenho)
    swagger-ui:
      enabled: false # DESATIVAR Swagger UI em PROD (segurança)