spring:
  application:
    name: Curso - Spring Boot Expert # Nome da aplicação

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Define 'dev' como o perfil ativo por padrão

  messages:
    encoding: UTF-8 # Codificação das mensagens
    basename: messages # Nome base dos arquivos .properties

  # Configurações Springdoc (OpenAPI/Swagger UI)
  springdoc:
    swagger-ui:
      path: /swagger # Caminho Swagger UI
      docExpansion: none # Expansão padrão UI
      filter: true # Habilitar filtro UI
      operationsSorter: method # Ordenar operações UI
      tagsSorter: alpha # Ordenar tags UI
    api-docs:
      path: /v3/api-docs # Caminho especificação OpenAPI JSON/YAML