spring:
  datasource: # Configuração do banco de dados para desenvolvimento (H2)
    driver-class-name: ${DATABASE_DRIVER} # Driver do DB
    url: ${DATABASE_URL} # URL de conexão do DB
    username: ${DATABASE_USERNAME} # Usuário do DB
    password: ${DATABASE_PASSWORD} # Senha do DB

  jpa:
    # Configuração do Hibernate (JPA)
    hibernate:
      # Estratégia DDL (update ou create-drop APENAS para DEV)
      ddl-auto: update
    show-sql: true # Exibir queries SQL (útil em DEV)
    properties:
      hibernate.dialect: ${HIBERNATE_DIALECT} # Dialeto Hibernate

  h2:
    console:
      enabled: true # Ativar console web H2 (em DEV)
      path: /h2-console # Caminho console H2

  springdoc:
    api-docs:
      enable: true # Ativar geração OpenAPI (em DEV)
    swagger-ui:
      enabled: true # Ativar Swagger UI (em DEV)