spring:
  application:
    name: Curso - Spring boot expert
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    encoding: UTF-8
    basename: messages